steps:
- id: 'Build app'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
          '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-app:${SHORT_SHA}',
          '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-app:latest',
          './app'
        ]

- id: 'Run unit test'
  name: 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-app:${SHORT_SHA}'
  entrypoint: python
  args: ['test.py', '-v']
  dir: 'app'

- id: 'Push app'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push',
          'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-app:${SHORT_SHA}'
        ]

#- id: 'Deploy app' # to new GCE instance
#  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#  entrypoint: 'gcloud'
#  timeout: 240s
#  args: ['compute', 'instances', 'create-with-container', 'vm-${SHORT_SHA}',
#          '--container-image',
#          'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-app:${SHORT_SHA}',
#          '--machine-type', 'f1-micro',
#          '--tags', 'allow-8090',
#        ]
#  env:
#    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'

- id: 'Create new release' # GKE
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  timeout: 240s
  args: ['deploy', 'releases', 'create', 'release-${SHORT_SHA}',
          '--delivery-pipeline', 'delivery-pipeline',
          '--region', 'us-central1',
          '--skaffold-file', 'skaffold.yaml',
        ]

serviceAccount: '${SERVICE_ACCOUNT}'
options:
  logging: CLOUD_LOGGING_ONLY
timeout:
  3600s