apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: my-app
deploy:
  kustomize:
    paths:
    - k8s/base
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - k8s/overlays/dev
- name: stage
  deploy:
    kustomize:
      paths:
      - k8s/overlays/stage
- name: prod
  deploy:
    kustomize: 
      paths: 
      - k8s/overlays/prod