apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: my-app
manifests:
  rawYaml:
  - k8s/base
#manifests:
#  kustomize:
#    paths:
#    - k8s/base
deploy:
  kubectl: {}
profiles:
- name: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
- name: prod
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
- name: stage
  manifests:
    kustomize:
      paths:
      - k8s/overlays/stage