apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: my-app
manifests:
  kustomize:
    paths:
    - k8s/base
deploy:
  kubectl: {}
  logs:
    prefix: container
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - k8s/overlays/dev
- name: stage
  deploy:
    kustomize:
      paths:
      - k8s/overlays/stage
- name: prod
  deploy:
    kustomize:
      paths:
      - k8s/overlays/prod