apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: my-app
deploy:
  kubectl: {}
profiles:
- name: dev
  manifests:
    rawYaml:
      - k8s/deployment-dev.yaml
- name: stage
  manifests:
    rawYaml:
      - k8s/deployment-stage.yaml
- name: prod
  manifests:
    rawYaml:
      - k8s/deployment-prod.yaml
