apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: my-app
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/perfect-victor-432019-p3/my-docker-repo/my-app
      context: app
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: ${PROJECT_ID}
#manifests:
#  kustomize:
#    paths:
#    - k8s/base
deploy:
  kubectl: {}
  kustomize:
    paths:
    - k8s/base
profiles:
- name: dev
  manifests:
    kustomize:
      paths:
      - k8s/overlays/dev
- name: prod
  manifests:
    kustomize:
      paths:
      - k8s/overlays/prod
- name: stage
  manifests:
    kustomize:
      paths:
      - k8s/overlays/stage