apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: my-app
profiles:
- name: dev
  deploy:
    manifests:
      kustomize:
        paths:
        - k8s/overlays/dev
- name: stage
  deploy:
    manifests:
      kustomize:
        paths:
        - k8s/overlays/stage
- name: prod
  deploy:
    manifests:
      kustomize:
        paths:
        - k8s/overlays/prod