apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: my-app
profiles:
- name: dev
  deploy:
    kubectl:
      manifests:
        kustomize:
          paths:
          - k8s/overlays/dev
- name: stage
  deploy:
    kubectl:
      manifests:
        kustomize:
          paths:
          - k8s/overlays/stage
- name: prod
  deploy:
    kubectl: 
      manifests:
        kustomize:
          paths:
          - k8s/overlays/prod