apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    spec:
      containers:
      - name: my-app
        image: us-central1-docker.pkg.dev/perfect-victor-432019-p3/my-docker-repo/my-app:latest
        ports:
        - containerPort: 8090
        env:
        - name: TARGET
          value: stage