apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: us-central1-docker.pkg.dev/perfect-victor-432019-p3/my-docker-repo/my-app
        resources:
          requests:
            memory: "32Mi"
            cpu: "0.1"
          limits:
            memory: "64Mi"
            cpu: "0.2"
        ports:
        - containerPort: 8090
        env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: TARGET
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090