apiVersion: v1
kind: Service
metadata:
  name: my-app
  #namespace: default
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
  selector:
    app: my-app