apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: us-central1-docker.pkg.dev/perfect-victor-432019-p3/my-docker-repo/my-app:latest
        ports:
        - containerPort: 8090
        env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TARGET
          value: stage
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090